import { Song } from '../types';

export const DEMO_SONGS: Song[] = [
  {
    id: 'demo-1',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    filename: 'Tekashi - Mr. 6ix9ine.mp3',
    title: 'Tekashi',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Clarke Oduor',
    year: '2020',
    durationMillis: 169000,
    durationFormatted: '2:49',
    artworkUri: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    isFavorite: true,
  },
  {
    id: 'demo-2',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    filename: 'Locked up pt. 2.mp3',
    title: 'Locked up pt. 2',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Akon, Daniel Hernandez',
    year: '2020',
    durationMillis: 203000,
    durationFormatted: '3:23',
    artworkUri: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    isFavorite: false,
  },
  {
    id: 'demo-3',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    filename: 'Tutu.mp3',
    title: 'Tutu',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Andrew Green',
    year: '2020',
    durationMillis: 164000,
    durationFormatted: '2:44',
    artworkUri: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    isFavorite: true,
  },
  {
    id: 'demo-4',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    filename: 'Gooba.mp3',
    title: 'Gooba',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Jahsei Onfroy',
    year: '2020',
    durationMillis: 252000,
    durationFormatted: '4:12',
    artworkUri: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
    isFavorite: false,
  },
  {
    id: 'demo-5',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    filename: 'Wait.mp3',
    title: 'Wait',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Tobee',
    year: '2020',
    durationMillis: 203000,
    durationFormatted: '3:23',
    artworkUri: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=600&auto=format&fit=crop&q=80',
    isFavorite: false,
  },
];
