import { Song } from '../types';

export const DEMO_SONGS: Song[] = [
  {
    id: 'demo-1',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    filename: 'Tekashi - Mr. 6ix9ine.mp3',
    title: 'Tekashi',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Clarke Oduor',
    year: '2020',
    durationMillis: 169000,
    durationFormatted: '2:49',
    artworkUri: null, // Will use default artwork
    isFavorite: true,
  },
  {
    id: 'demo-2',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    filename: 'Locked up pt. 2.mp3',
    title: 'Locked up pt. 2',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Akon, Daniel Hernandez',
    year: '2020',
    durationMillis: 203000,
    durationFormatted: '3:23',
    artworkUri: null,
    isFavorite: false,
  },
  {
    id: 'demo-3',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    filename: 'Tutu.mp3',
    title: 'Tutu',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Andrew Green',
    year: '2020',
    durationMillis: 164000,
    durationFormatted: '2:44',
    artworkUri: null,
    isFavorite: true,
  },
  {
    id: 'demo-4',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    filename: 'Gooba.mp3',
    title: 'Gooba',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Jahsei Onfroy',
    year: '2020',
    durationMillis: 252000,
    durationFormatted: '4:12',
    artworkUri: null,
    isFavorite: false,
  },
  {
    id: 'demo-5',
    uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    filename: 'Wait.mp3',
    title: 'Wait',
    artist: 'Mr. 6ix9ine',
    album: 'Tattle Tales',
    composer: 'Daniel Hernandez, Tobee',
    year: '2020',
    durationMillis: 203000,
    durationFormatted: '3:23',
    artworkUri: null,
    isFavorite: false,
  },
];
